steps:
  # Pull cache image pour accélérer le build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker pull us-central1-docker.pkg.dev/market360-492002/market360/api:cache || true

  # Build avec cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - market360-infra/Dockerfile
      - --cache-from=us-central1-docker.pkg.dev/market360-492002/market360/api:cache
      - -t
      - us-central1-docker.pkg.dev/market360-492002/market360/api:latest
      - -t
      - us-central1-docker.pkg.dev/market360-492002/market360/api:$COMMIT_SHA
      - -t
      - us-central1-docker.pkg.dev/market360-492002/market360/api:cache
      - .

  # Push toutes les tags (latest, commit SHA, cache)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/market360-492002/market360/api

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - market360
      - --image=us-central1-docker.pkg.dev/market360-492002/market360/api:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
